# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  # host: <%= ENV["DATABASE_HOSTNAME"] || "localhost" %>
  # port: 3306
  username: "root"
  password: "xuanpham"

development:
  <<: *default
  database: react_development

test:
  <<: *default
  database: react_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
